### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by marcusdevcode** [SergeIpatyev/svalidatejs#1]
Hi. Can you please add this plugin to the bower website https://bower.io/docs/creating-packages/

**Comment by rootiss** [comment]
Hi, thank you. Sorry, I could not answer right away. But you can see now https://github.com/SergeIpatyev/svalidatejs 
To install via Bower, simply do the following:
$ bower install svalidate
To install via npm: 
$ npm install svalidate
04.08.2017, 16:11
-- Thank you)------http://ipatieff.me/
